SELECT
    CONTAINER_ID,
    TEMPERATURE_C,
    HUMIDITY_PCT,
    VIBRATION_LEVEL,
    TIMESTAMP,
    CASE
        WHEN TEMPERATURE_C > 30 THEN 'HIGH'
        ELSE 'NORMAL'
    END AS TEMPERATURE_STATUS
FROM ATMOSYNC_DB.PUBLIC.SENSOR_DATA